[package]
name = "stack-param"
version = "0.1.0"
authors = ["Chad Retz <chad.retz@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2"
jni-sys = "0.2"
log = "0.3"
env_logger = "0.3"